name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente à meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar animação da cobra
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: HugoMDKK
          outputs: dist/snake.svg

      - name: Fazer commit e push da animação
        run: |
          git config --global user.email "seu-email@gmail.com"
          git config --global user.name "HugoMDKK"
          git add dist/snake.svg
          git commit -m "Atualizando Snake Animation"
          git push
